server:
  port: 8080
  servlet:
    context-path: /api
#  ssl:
#    enabled: true
#    key-store-password: 970827351Yd
#    key-store: classpath:www.tsondy.club.jks
#    key-store-type: JKS
#    ciphers: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_RC4_128_SHA,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA,SSL_RSA_WITH_RC4_128_SHA
#
#condition:
#  http2https: true
#http:
#  port: 8080

spring:
    datasource:
        name: mysql_test
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          # driver-class-name: com.mysql.jdbc.Driver
          #基本属性
#          url: jdbc:mysql://49.234.239.133:3306/tson?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          url: jdbc:mysql://localhost:3306/tson?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Hongkong
          username: root
          password: 970827351Yd
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20

    mail:
      host: smtp.qq.com #发送邮件服务器
      username: 1879639904@qq.com #发送邮件的邮箱地址
      password:  jsgsdkcxaurbechh #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
      properties.mail.smtp.port: 465 #端口号465或587
      from: 1879639904@qq.com # 发送邮件的地址，和上面username一致可以任意
      properties.mail.smtp.starttls.enable: true
      properties.mail.smtp.starttls.required: true
      properties.mail.smtp.ssl.enable: true
      default-encoding: utf-8


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tson.yd.model

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

